name: Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code for this repository
        uses: actions/checkout@v3

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'repo'
          scan-ref: './'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
